services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
